layout_spectrum: 0.9572151
typography_spectrum: 0.1056546
color:
  saturation: 0.4016109
  lightness: 0.7328361
  brandStrength: 0.7129934
  rhythmicContrast: 0.7370422
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Our Life Story
